#!/usr/bin/env bash
elm make ./src/Powerball.elm --output ../../../priv/static/js/powerball.js --optimize
uglifyjs ../../../priv/static/js/powerball.js --compress "pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters,keep_fargs=false,unsafe_comps,unsafe" | uglifyjs --mangle --output=../../../priv/static/js/powerball.min.js

elm make ./src/GoldLotto.elm --output ../../../priv/static/js/gold-lotto.js --optimize
uglifyjs ../../../priv/static/js/gold-lotto.js --compress "pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters,keep_fargs=false,unsafe_comps,unsafe" | uglifyjs --mangle --output=../../../priv/static/js/gold-lotto.min.js

elm make ./src/DailyChart.elm --output ../../../priv/static/js/daily-chart.js --optimize
uglifyjs ../../../priv/static/js/daily-chart.js --compress "pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters,keep_fargs=false,unsafe_comps,unsafe" | uglifyjs --mangle --output=../../../priv/static/js/daily-chart.min.js

elm make ./src/GoogleRank.elm --output ../../../priv/static/js/google-rank.js --optimize
uglifyjs ../../../priv/static/js/google-rank.js --compress "pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters,keep_fargs=false,unsafe_comps,unsafe" | uglifyjs --mangle --output=../../../priv/static/js/google-rank.min.js
