#!/usr/bin/env bash
elm make ./src/Powerball.elm --output ../../../priv/static/js/powerball.js --optimize
uglifyjs ../../../priv/static/js/powerball.js --compress "pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters,keep_fargs=false,unsafe_comps,unsafe" | uglifyjs --mangle --output=../../../priv/static/js/powerball.min.js

elm make ./src/Asx200.elm --output ../../../priv/static/js/asx200.js --optimize
uglifyjs ../../../priv/static/js/asx200.js --compress "pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters,keep_fargs=false,unsafe_comps,unsafe" | uglifyjs --mangle --output=../../../priv/static/js/asx200.min.js